### ISSUE TITLE
Direct link video previews are not supported on the asset library

### ISSUE THREAD

**Issue by Calinou** [NovaDC/Godot-AdvancedBillboard#1]
Hello,

Direct link video previews are not supported on the asset library, so the preview here has been removed: https://godotengine.org/asset-library/asset/3446

Please use a YouTube link or a GIF instead.

**Comment by NovaDC** [comment]
Understood. Are unlisted (not privated) Youtube videos ok to use?

**Comment by Calinou** [comment]
> Are unlisted (not privated) Youtube videos ok to use?

Sure :slightly_smiling_face:

**Comment by NovaDC** [comment]
Assetlib page updated ^w^
